repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml          # Проверка синтаксиса YAML
      - id: end-of-file-fixer   # Убедиться в наличии пустой строки в конце файла
        exclude: \.(log|bin|png|jpg|pdf|log.*)$
      - id: trailing-whitespace # Удалить пробелы в конце строк
        exclude: \.(log|bin|png|jpg|pdf|log.*)$

  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   rev: v0.5.6
  #   hooks:
  #     - id: ruff
  #       args: [--fix]
  #     - id: ruff-format

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.10.0
  #   hooks:
  #     - id: mypy
  #       # args: [--strict, --ignore-missing-imports, --show-error-codes]  # --strict
  #       args: [
  #         --config-file=price_flow/pyproject.toml,  # Используем конфиг из проекта
  #         --show-error-codes,
  #         --no-error-summary
  #       ]
  #       additional_dependencies:
  #         - pydantic
  #         - pydantic-settings
  #         - types-python-dateutil
  #         - types-requests
  #         - sqlalchemy-stubs  # Если используете SQLAlchemy
  #       # files: ^src/  # Проверяем только src
  #       exclude: ^tests/|^alembic/  # Исключаем тесты и миграции

  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.7.7
  #   hooks:
  #     - id: bandit
  #       args: ["-r", "src/"]
