services:
  price_flow:
    volumes:
      - ./price_flow/src:/app/src
    env_file:
      - ./.env.price_flow
    ports:
     - 8000:8000
  converter:
    volumes:
      - ./converter/src:/opt/app
    env_file:
      - ./.env.converter
    ports:
     - 8090:8000

  redis:
    ports:
     - 6379:6379
