services:
  price_flow:
    build:
      context: ./price_flow
      dockerfile: Dockerfile
  converter:
    build:
      context: ./converter
      dockerfile: Dockerfile
  redis:
    image: redis:7-alpine
    command: redis-server --notify-keyspace-events AKE
